### ISSUE TITLE
Cleanup generated k8s manifests

### ISSUE THREAD

**Issue by marcinc** [appvia/kev#397]
Currently some K8s manifests generated by the tool also 
include the following keys:

status: {}
creationTimestamp: null

These aren't necessary and could potentially create issues down the line.

Exclude the fields above when rendering k8s manifests.

**Comment by mangas** [comment]
Both empty status and null timestamp seem to be working as intended since they are not "nullable" on the k8s api library. Since this is how they are intended to be populated I would guess that if we've seen any issues those would probably be due to some mishandling of these types and maybe we should look into whatever was failing in that case? What do you think ?

**Comment by marcinc** [comment]
Closing this for now as this doesn't seem to be blocking anything.
